### ISSUE TITLE
License missing from repo

### ISSUE THREAD

**Issue by karan** [joe-re/dotfiles#1]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by joe-re** [comment]
I added license.txt. b4be94d04f9d64728dd396534a0cbc8b47136c3f

Thanks for your advice. :smiley:
